name: Tsurlfilter

on:
  push:
#    branches:
#      /^v\d+\.\d+\.\d+$/

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versioc: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: npm test
        run: npm run test:prod

      - name: npm build
        run: npm run build

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        run: npm run travis-deploy-once "npm run report-coverage"
